In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/content/diamonds.csv",sep=",")

In [3]:
df.head()

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  
0  2.43  
1  2.31  
2  2.31  
3  2.63  
4  2.75

In [18]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [19]:
df.shape

(53940, 10)

In [20]:
df_clean = df.select_dtypes(exclude ='object')

In [21]:
df_clean.shape

(53940, 7)

In [22]:
df_clean.columns

Index(['carat', 'depth', 'table', 'price', 'x', 'y', 'z'], dtype='object')

In [23]:
X = df_clean

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test = train_test_split(X,test_size=0.3,random_state=42)

In [26]:
X_train.shape, X_test.shape

((37758, 7), (16182, 7))

In [29]:
from sklearn.cluster import KMeans
KM = KMeans(n_clusters=2, random_state=42)



In [30]:
KM.fit(X_train)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=2, random_state=42)

In [31]:
KM.cluster_centers_ # centroid for every column

array([[1.53060991e+00, 6.17111270e+01, 5.77860449e+01, 1.10482671e+04,
        7.33325382e+00, 7.33399943e+00, 4.52025853e+00],
       [6.33405404e-01, 6.17526157e+01, 5.73871704e+01, 2.33610697e+03,
        5.37166336e+00, 5.37572683e+00, 3.31828462e+00]])

In [32]:
KM.inertia_

173196144126.17523

In [33]:
KM.labels_ # all labels for data point

array([0, 1, 0, ..., 1, 1, 1], dtype=int32)

In [34]:
KM.labels_.min(),KM.labels_.max()

(0, 1)

In [35]:
pred = KM.predict(X_test)

In [36]:
pred

array([1, 1, 1, ..., 0, 1, 1], dtype=int32)

In [37]:
pred.min(),pred.max()

(0, 1)